### ISSUE TITLE
Fix quote styles on Vim theme

### ISSUE THREAD

**Issue by moll** [jarmo/hackersays#38]

**Comment by jarmo** [comment]
@moll what's wrong with the current style? Any news with the fix?

**Comment by moll** [comment]
I asked the design agency responsible for this and they don't remember either. Yay!

**Comment by jarmo** [comment]
Maybe design agency meant that quotes are upside-down (not just in the vim theme, but in every theme)?

**Comment by moll** [comment]
As in there's an end-quote where you think there should be a begin-quote?

**Comment by jarmo** [comment]
Probably, yes.

**Comment by moll** [comment]
God knows. They're upside-down in every UI for style reasons. Even here in GitHub, above the comment box. ^_^

**Comment by jarmo** [comment]
Where can we submit issues for GitHub? :)
