### ISSUE TITLE
Ca I use your quote?

### ISSUE THREAD

**Issue by TuxmAL** [jarmo/hackersays#43]
Can I use your quote in my tweet, providing that every 5 quotes I will cite your site.
I will use'em in my projects: 
https://github.com/TuxmAL/dice-api 
and his client 
https://github.com/TuxmAL/chirpmotd
Thanks for your attention

**Comment by jarmo** [comment]
Feel free to do it by using one of our non-official API endpoints ([one random quote](http://hackersays.com/quote) / [ten random quotes](http://hackersays.com/quotes)).

**Comment by TuxmAL** [comment]
Thanks! @jarmo
